# Generated by Django 5.2.5 on 2025-08-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='stocks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='backend.stock'),
        ),
    ]
